# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fitchain.io
title: fitchain
email: hello@fitchain.io
author: Francesco Gadaleta
description: "A Decentralized Machine Learning Factory"
copyright: 'Copyright &copy; 2017 fitchain.io All Rights Reserved.'
credits: 'Credits: amethix.com'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/amethixtech
  - title: github
    url: https://github.com/amethix
  - title: linkedin
    url:
